---
title: "Tratamento de Dados da base MUNIC para pesquisa sobre capacidades e resposta climática"
authors: "Luiz C Soares e Pedro Aquino
---

# Configuração

## Pacotes necessários

Nesta seção serão baixados os pacotes que serão utilizados no processamento destes dados

```{r}
"install.packakges('here')
install.packakges('httr')
install.packakges('usethis') 
install.packakges('readODS')
install.packakges('tidyverse')
install.packakges('labelled')"
```

```{r}
library(here)
library(httr)
library(usethis) 
library(readODS)
library(tidyverse)
library(labelled)
library(ggplot2)
```

## Configuração de ambiente

```{r}
create_project(".")

use_readme_md()

use_gpl3_license()
```

# Importando dados

Os dados da MUNIC 2020 estão disponíveis na página do IBGE:

-   2013: https://ftp.ibge.gov.br/Perfil_Municipios/2013/base_MUNIC_ods_2013.zip

-   2017: https://ftp.ibge.gov.br/Perfil_Municipios/2017/Base_de_Dados/Base_MUNIC_2017_ods.zip

-   2020: https://ftp.ibge.gov.br/Perfil_Municipios/2020/Base_de_Dados/Base_MUNIC_2020.ods

```{r}

url_2013 <- "https://ftp.ibge.gov.br/Perfil_Municipios/2013/base_MUNIC_ods_2013.zip"

url_2017 <- "https://ftp.ibge.gov.br/Perfil_Municipios/2017/Base_de_Dados/Base_MUNIC_2017_ods.zip"


url_2020 <- "https://ftp.ibge.gov.br/Perfil_Municipios/2020/Base_de_Dados/Base_MUNIC_2020.ods"


urls_dados <- list(url_2013, url_2017, url_2020)

pasta_originais <- here("dados_originais")

if(!dir.exists(pasta_originais))
    {dir.create(pasta_originais)}

for(link in urls_dados){
    out_file = file.path(pasta_originais, basename(link))
    if(!file.exists(out_file)){
download.file(
    url = link, 
    destfile = file.path(pasta_originais, basename(link)), 
    mode = "wb")
    }
}

```

Descompactando arquivos

```{r}
arquivos_zip <- list.files(pasta_originais, pattern = "\\.zip$", full.names = TRUE)

for (zip_file in arquivos_zip) {
  unzip(zip_file, exdir = pasta_originais)
}
```

# Selecionando planilhas de interesse

### 2013

```{r}
munic_2013 <- read_ods(here(pasta_originais, "base.ods"), sheet = "Gestão de riscos")

munic_2013 <- munic_2013 |>
    select(A1, A183, A184, A185, 
           A186, A187, A188, A189, 
           A190, A196, A197, A198, 
           A199, A202, A206, A207, 
           A208, A209, A211, A220, 
           A221, A225) 

munic_2013 <- munic_2013 |>
    set_variable_labels(
      A1 = "Código do Município", 
      A183 = "Plano Diretor contempla enchentes e inundações?", 
      A186 = "Plano Diretor contempla escorramento e deslizamento?", 
      A189 = "Tem plano municipal de redução de riscos?", 
      A190 = "Tem carta geotécnica de aptidão à urbanização?", 
      A196 = "Tem mapeamento de área de risco de enchentes ou inundações?", 
      A198 = "Tem mecanismos de controle para evitar ocupação em área suscetível a desastres?", 
      A199 = "Tem plano de contingência?",
      A202 = "Tem cadastro de risco?",  
      A206 = "Tem mapeamento de área de risco em encosta?", 
      A208 = "Tem mecanismos de controle para evitar ocupação em área suscetível a desastre nas encostas?", 
      A209 = "Tem plano de contingência para desastres em encostas?", 
      A211 = "Tem sistema de alerta antecipado para deslizamento de encostas?", 
      A220 = "Tem unidade do corpo de bombeiros?", 
      A221 = "Tem coordenação municipal de defesa civil?",
      A225 = "Tem núcleos comunitários de defesa civil?", 
      A184 = "Tem lei de uso e ocupação do solo para enchentes ou inundações?", 
      A185 = "Tem lei específica para enchentes ou inundações", 
      A187 = "Tem lei de uso e ocupação do solo para escorregamentos ou deslizamento de encostas?", 
      A188 = "Tem lei específica para escorregamento ou deslizamento de encosta?", 
      A197 = "Tem programa habitacional para realocação de população em área de risco de enchente ou inundação?", 
      A207 = "Tem programa habitacional para realocação de população em área de risco de escorregamento ou deslizamento?"
    )
```

### 2017

```{r}
munic_2017 <- read_ods(here(pasta_originais, "base.ods"), sheet = "Gestão de riscos")
munic_2017 <- munic_2017 |>
    select(CodMun, MGRD171, MGRD172, MGRD173,
            MGRD174, MGRD175, MGRD176, MGRD177, 
            MGRD178, MGRD181, MGRD182, MGRD183, 
            MGRD184, MGRD187, MGRD191, MGRD192,
            MGRD193, MGRD194, MGRD196, MGRD201, 
            MGRD202, MGRD203) 

munic_2017 <- munic_2017 |>
    set_variable_labels(
      CodMun = "Código do Município", 
      MGRD171 = "Plano Diretor contempla enchentes e inundações?", 
      MGRD172 = "Tem lei de uso e ocupação do solo para enchentes ou inundações?", 
      MGRD173 = "Tem lei específica para enchentes ou inundações?", 
      MGRD174 = "Plano Diretor contempla escorramento e deslizamento?", 
      MGRD175 = "Tem lei de uso e ocupação do solo para escorregamentos ou deslizamento de encostas?", 
      MGRD176 = "Tem lei específica para escorregamento ou deslizamento de encosta?", 
      MGRD177 = "Tem plano municipal de redução de riscos?",
      MGRD178 = "Tem carta geotécnica de aptidão à urbanização?",  
      MGRD181 = "Tem mapeamento de área de risco de enchentes ou inundações?", 
      MGRD182 = "Tem programa habitacional para realocação de população em área de risco de enchente ou inundação?", 
      MGRD183 = "Tem mecanismos de controle para evitar ocupação em área suscetível a desastres?", 
      MGRD184 = "Tem plano de contingência?", 
      MGRD187 = "Tem cadastro de risco?", 
      MGRD191 = "Tem mapeamento de área de risco em encosta?",
      MGRD192 = "Tem programa habitacional para realocação de população em área de risco de escorregamento ou deslizamento?", 
      MGRD193 = "Tem mecanismos de controle para evitar ocupação em área suscetível a desastre nas encostas?", 
      MGRD194 = "Tem plano de contingência para desastres em encostas?", 
      MGRD196 = "Tem sistema de alerta antecipado para deslizamento de encostas?", 
      MGRD201 = "Tem unidade do corpo de bombeiros?", 
      MGRD202 = "Tem coordenação municipal de defesa civil?", 
      MGRD203 = "Tem núcleos comunitários de defesa civil?"
    )
```

### 2020

```{r}
munic_2020 <- read_ods(here(pasta_originais, "base.ods"), sheet = "Gestão de riscos")
munic_2020 <- munic_2020 |>
    select(CodMun, Mgrd171, Mgrd172, Mgrd173,
            Mgrd174, Mgrd75, Mgrd176, Mgrd177, 
            Mgrd178, Mgrd181, Mgrd182, Mgrd183, 
            Mgrd184, Mgrd187, Mgrd201, Mgrd202,
            Mgrd203, Mgrd204, Mgrd206, Mgrd211, 
            Mgrd212, Mgrd213) 

munic_2020 <- munic_2020 |>
    set_variable_labels(
      CodMun = "Código do Município", 
      Mgrd171 = "Plano Diretor contempla enchentes e inundações?", 
      Mgrd172 = "Tem lei de uso e ocupação do solo para enchentes ou inundações?", 
      Mgrd177 = "Tem plano municipal de redução de riscos?", 
      Mgrd178 = "Tem carta geotécnica de aptidão à urbanização?", 
      Mgrd181 = "Tem mapeamento de área de risco de enchentes ou inundações?", 
      Mgrd183 = "Tem mecanismos de controle para evitar ocupação em área suscetível a desastres?", 
      Mgrd184 = "Tem plano de contingência?",
      Mgrd187 = "Tem cadastro de risco?",  
      Mgrd201 = "Tem mapeamento de área de risco em encosta?", 
      Mgrd203 = "Tem mecanismos de controle para evitar ocupação em área suscetível a desastre nas encostas?", 
      Mgrd204 = "Tem plano de contingência para desastres em encostas?", 
      Mgrd206 = "Tem sistema de alerta antecipado para deslizamento de encostas?", 
      Mgrd211 = "Tem unidade do corpo de bombeiros?", 
      Mgrd212 = "Tem coordenação municipal de defesa civil?",
      Mgrd213 = "Tem núcleos comunitários de defesa civil?", 
      Mgrd174 = "Plano Diretor contempla escorramento e deslizamento?", 
      Mgrd173 = "Tem lei específica para enchentes ou inundações", 
      Mgrd175 = "Tem lei de uso e ocupação do solo para escorregamentos ou deslizamento de encostas?", 
      Mgrd176 = "Tem lei específica para escorregamento ou deslizamento de encosta?", 
      Mgrd182 = "Tem programa habitacional para realocação de população em área de risco de enchente ou inundação?", 
      Mgrd202 = "Tem programa habitacional para realocação de população em área de risco de escorregamento ou deslizamento?"
    )
```

## Juntar as três tabelas

```{r}

```

# Gráficos descritivos

```{r}
munic_2013 |>
    group_by(A220) |>
    summarise(Ocorrencias = n()) |>
    ggplot(
        aes(x = A220, y = Ocorrencias))+
        geom_col()+
        theme_bw()
```

# Análise
